name: atu
channels:
  - defaults
  - cornell-zhang
  - pytorch
  - conda-forge
dependencies:
  - python=3.8
  - pytorch 
  - torchvision 
  - torchaudio 
  - cudatoolkit=10.2
  - black
  - heterocl
  - future
  - plotly
  - patchelf
  - pip:
      - tensorboard
      - gym
      - mujoco-py<2.2,>=2.1


