#!bin/bash
# python atu/hj_sac.py --use-hj --track --reward-shape-penalty 10 --seed 0 --train-dist "0.1,0.1,0.1" --eval-dist  "0.1,0.1,0.1" --env-id Safe-DubinsHallway-v2 --capture-video
# python atu/hj_sac.py --use-hj --track --reward-shape-penalty 10 --seed 0 --train-dist "0.1,0.1,0.1" --eval-dist  "0.1,0.1,0.1" --env-id Safe-DubinsHallway-v2 --capture-video --gamma 0.9
# python atu/hj_sac.py --use-hj --track --reward-shape-penalty 10 --seed 0 --train-dist "0.1,0.1,0.1" --eval-dist  "0.1,0.1,0.1" --env-id Safe-DubinsHallway-v2 --capture-video --gamma 0.9 --batch-size 512 --reward-shape
# python atu/hj_sac.py --use-hj --track --reward-shape-penalty 10 --seed 0 --train-dist "0.1,0.1,0.1" --eval-dist  "0.1,0.1,0.1" --env-id Safe-DubinsHallway-v2 --capture-video --gamma 0.9 --batch-size 512  --reward-shape --reward-shape-gradv --seperate-cost
# python atu/hj_sac.py --use-hj --track --reward-shape-penalty 1 --seed 0 --train-dist "0.1,0.1,0.1" --eval-dist  "0.1,0.1,0.1" --env-id Safe-DubinsHallway-v2 --capture-video --gamma 0.9 --batch-size 512  --reward-shape --reward-shape-gradv --seperate-cost
# python atu/hj_sac.py --use-hj --track --reward-shape-penalty 0 --seed 0 --train-dist "0.1,0.1,0.1" --eval-dist  "0.1,0.1,0.1" --env-id Safe-DubinsHallway-v2 --capture-video --gamma 0.9 --batch-size 512  --reward-shape --reward-shape-gradv --seperate-cost --reward-shape-gradv-takeover 1
# python atu/hj_sac.py --use-hj --track --reward-shape-penalty 0 --seed 0 --train-dist "0.1,0.1,0.1" --eval-dist  "0.1,0.1,0.1" --env-id Safe-DubinsHallway-v2 --capture-video --gamma 0.9 --batch-size 512  --reward-shape --reward-shape-gradv --seperate-cost --reward-shape-gradv-takeover 10
# python atu/hj_sac.py --use-hj --track --reward-shape-penalty 0 --seed 0 --train-dist "0.1,0.1,0.1" --eval-dist  "0.1,0.1,0.1" --env-id Safe-DubinsHallway-v2 --capture-video --gamma 0.9 --batch-size 512  --reward-shape --reward-shape-gradv --seperate-cost --reward-shape-gradv-takeover 20
# python atu/hj_sac.py --use-hj --track --reward-shape-penalty 0 --seed 0 --train-dist "0.1,0.1,0.1" --eval-dist  "0.1,0.1,0.1" --env-id Safe-DubinsHallway-v2 --capture-video --gamma 0.9 --batch-size 512  --reward-shape --reward-shape-gradv --seperate-cost --reward-shape-gradv-takeover 30
# python atu/hj_sac.py --use-hj --track --reward-shape-penalty 0 --seed 0 --train-dist "0.1,0.1,0.1" --eval-dist  "0.1,0.1,0.1" --env-id Safe-DubinsHallway-v2 --capture-video --gamma 0.9 --batch-size 512  --reward-shape --reward-shape-gradv --seperate-cost --reward-shape-gradv-takeover 40
# python atu/hj_sac.py --use-hj --track --reward-shape-penalty 0 --seed 0 --train-dist "0.1,0.1,0.1" --eval-dist  "0.1,0.1,0.1" --env-id Safe-DubinsHallway-v2 --capture-video --gamma 0.9 --batch-size 512  --reward-shape --reward-shape-gradv --seperate-cost --reward-shape-gradv-takeover 50
# python atu/hj_sac.py --use-hj --track --seed 0 --train-dist "0.1,0.1,0.1" --eval-dist  "0.1,0.1,0.1" --env-id Safe-DubinsHallway-v2 --capture-video --gamma 0.9 --batch-size 512  --reward-shape 
# python atu/hj_sac.py --use-hj --track --seed 0 --train-dist "0.1,0.1,0.1" --eval-dist  "0.1,0.1,0.1" --env-id Safe-DubinsHallway-v2 --capture-video --gamma 0.9 --batch-size 512  --reward-shape  --reward-shape-penalty 20

python atu/hj_sac.py --use-hj --track --seed 0 --train-dist "0.1,0.1,0.1" --eval-dist  "0.1,0.1,0.1" --env-id Safe-DubinsHallway-v2 --capture-video --gamma 0.9 --batch-size 512 