wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.11
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.12
    start_time: 1649181971
    t:
      1:
      - 1
      2:
      - 1
      3:
      - 13
      - 16
      - 35
      4: 3.8.12
      5: 0.12.11
      8:
      - 5
alpha:
  desc: null
  value: 0.2
autotune:
  desc: null
  value: true
batch_size:
  desc: null
  value: 256
beta:
  desc: null
  value: 0.1
buffer_size:
  desc: null
  value: 1000000
capture_video:
  desc: null
  value: true
cuda:
  desc: null
  value: true
done_if_unsafe:
  desc: null
  value: false
env_id:
  desc: null
  value: Safe-Pendulum-v1
exp_name:
  desc: null
  value: sac
exploration_noise:
  desc: null
  value: 0.1
gamma:
  desc: null
  value: 0.99
hj_stop_steps:
  desc: null
  value: 2147483647
lagrange:
  desc: null
  value: false
learning_starts:
  desc: null
  value: 5000
max_grad_norm:
  desc: null
  value: 0.5
noise_clip:
  desc: null
  value: 0.5
policy_frequency:
  desc: null
  value: 2
policy_lr:
  desc: null
  value: 0.0003
q_lr:
  desc: null
  value: 0.001
reward_shape:
  desc: null
  value: false
seed:
  desc: null
  value: 1
target_network_frequency:
  desc: null
  value: 1
tau:
  desc: null
  value: 0.005
torch_deterministic:
  desc: null
  value: true
total_timesteps:
  desc: null
  value: 15000
track:
  desc: null
  value: true
use_hj:
  desc: null
  value: false
wandb_entity:
  desc: null
  value: null
wandb_project_name:
  desc: null
  value: atu
